name: Validate pip requirements-fixed.txt

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: refs/pull/${{ github.event.pull_request.number }}/head
          path: ncs/nrf
          fetch-depth: 0

      - name: Determine PR Origin
        id: pr-origin
        run: |
          echo "pr_repo_owner=${{ github.event.pull_request.head.repo.owner.login }}" >> $GITHUB_OUTPUT

      - name: Commit and push changes
        uses: actions/checkout@v3
        working-directory: ncs/nrf
        run: |
          echo test >> test
          git config --global user.email "NordicBuilder@github.com"
          git config --global user.name "NordicBuilder"
          git add ./test
          git commit -F- <<EOF
          Update requirements-fixed.txt from NordicBuilder

          Automatically upload changed requirements-fixed.txt

          Signed-off-by: Nordic Builder <NordicBuilder@nordicsemi.no>
          EOF
          git remote set-url origin https://NordicBuilder:${{ secrets.NCS_GITHUB_TOKEN }}@github.com/${{ steps.pr-origin.outputs.pr_repo_owner }}/sdk-nrf-testing.git
          git push origin HEAD:${{ github.head_ref }}
